### ISSUE TITLE
Set Nefit easy operating mode

### ISSUE THREAD

**Issue by edautz** [sweebee/pimatic-nefit#2]
I installed your plug-in today.
Nice work.

During installation the coffee script was compiled after Pimatic was started. To create a device, I had to restart Pimatic again.

The device works good.

I also tried to make rules:

set temp of Nefit-easy to 20, doesn’t throw an error.

But 

set mode of Nefit-easy to user-mode clock 

or 

set mode of Nefit-easy to clock

throws an error.

Is there a way to change the mode by a rule?

**Comment by sweebee** [comment]
You can do the following:

```
set mode of thermostaat to "clock"
```
```
set mode of thermostaat to "manual"
```

**Comment by sweebee** [comment]
updated the readme

**Comment by edautz** [comment]
Sorry,

But this doesn’t work:

Could not find an provider that provides the next action of "set mode of Nefit-easy to “auto”".

Could not find an provider that provides the next action of "set mode of Nefit-easy to "manual”".

**Comment by edautz** [comment]
Set mode of Nefit-easy to "clock" 
and “manual” works as a charm.

But 

When
every 1minutes and mode of Nefit-easy is equal to manu (or auto or boost???) 

doesn’t work. No syntax error but simply no action.

I see in the history that this commands were used in previous versions.

But


every 1minutes and $nefit.mode = "manual" or "clock" works!

**Comment by sweebee** [comment]
auto, manu and boost is not possible. Only manual and clock.

**Comment by edautz** [comment]
I understanding your intention but in this version of the code you can make a  condition of a rule:

every 1 minutes and mode of Nefit-easy is equal to manu/auto/boost.

That condition doesn’t work. I suggest to change the code in 

mode of <thermostat> is equal to clock/manual,

so this condition can work.

**Comment by sweebee** [comment]
yes I see, need to fix that.

**Comment by sweebee** [comment]
released a new version, should work now.
